### ISSUE TITLE
fix DFD

### ISSUE THREAD

**Issue by bwolatz** [bwolatz/CSCI4900#10]
change "Other Pom.xml" to "Maven Central"

change "Jar Files and Dependencies" to "Jar Files and dependent Pom.xml files"

change "dependencies" to "coordinates"

change "pull request" (from Maven plugin to DoSOCS) to "notify of changes"

delete lines "Check Dependencies" and "Yes/No"

change box type of "Temp Dir" to the same as "SPDX", since they are both databases

change box type of "DoSOCS" and "Maven Central" to the same as "Person", since all 3 are external actors and we aren't working with their process as much as we are just using it

break apart "Maven Plugin" into specific actions. Break into processes like "Read Pom.xml and get Dependencies/Coordinates", "Send JARs to Temp", etc. and fix lines accordingly.

**Comment by nadusumilli-unomaha** [comment]
I have dont most of it. I dint understand the last part. ![image](https://cloud.githubusercontent.com/assets/11622664/13302082/a88b8382-db0d-11e5-8abb-561b2a4fcdda.png)
