### ISSUE TITLE
Fix DFD

### ISSUE THREAD

**Issue by bwolatz** [bwolatz/CSCI4900#15]
Change "Notify of Changes" to "Dependency Tree"

Remove "RELEVANT DEPENDENCY TREE"

Change SPDX -> DoSOCS from "Packages" to something else (I'm not exactly sure what it would be)

**Comment by nadusumilli-unomaha** [comment]
Made Changes please check and see if it looks good.

**Comment by bwolatz** [comment]
Maybe just change SPDX to DoSOCS from "Package" to "Spec Sheet"

**Comment by nadusumilli-unomaha** [comment]
Split ‘Get Jar Files’ into the two processes it is doing>> 
1) Getting Jar Files and

2) Creating Tree. 

Get Jar Files also has to send the Temp Dir location to DoSOCS.

**Comment by bwolatz** [comment]
arrow coming out of "Parse XML" that goes to new action box "Create Dependency Tree" with the label "pom.xml". "Create Dependency Tree" has an arrow going to Maven Central with "pom.xml" and an arrow coming back with "dependency info". "Create Dependency Tree" has an arrow going to "DoSOCS" with "dependency document" and an arrow going to "Temp Dir" with "Dependency Info". The arrow from "Get Jar Files" to "DoSOCS" with "Dependency Tree" can be reomved.

**Comment by bwolatz** [comment]
didn't mean to close

**Comment by nadusumilli-unomaha** [comment]
![image](https://cloud.githubusercontent.com/assets/11622664/14574510/ba34028a-0321-11e6-8355-6b2faddd92e3.png)

changes have been made to the dfd
