### ISSUE TITLE
lower level dependencies

### ISSUE THREAD

**Issue by nadusumilli-unomaha** [bwolatz/CSCI4900#20]
Copy the pom.xml of all the downloaded dependencies and run the scan again.

**Comment by bwolatz** [comment]
What is the the method of getting the other pom.xml's from the first one?

**Comment by nadusumilli-unomaha** [comment]
-DcopyPom=true was supposed to do that but i am not able to do it. I have to do a little more work on that.

**Comment by bwolatz** [comment]
these are all gathered by the mvn:dependency-tree. I will write a script that can judge the levels of dependency and only include those at levels 1 2 and 3
