### ISSUE TITLE
Write a script to determine dependency level from tree

### ISSUE THREAD

**Issue by bwolatz** [bwolatz/CSCI4900#22]
given a dependency tree in text format (returned by maven), parse this and createe a data structure holding only the dependencies at levels 1 through 3 in the tree (then run dosocs on every jar in that data structure)

**Comment by bwolatz** [comment]
just need to get the package id from dosocs output to run 'dosocs2 generate <package id>'

suggestions?

**Comment by nadusumilli-unomaha** [comment]
We have to create a dependency document based on the tree structure.

**Comment by bwolatz** [comment]
done in class today
