### ISSUE TITLE
Is there a way get package ID for every dependency?

### ISSUE THREAD

**Issue by bwolatz** [bwolatz/CSCI4900#36]
So we got the output to print for one or two dependencies when we run our program. It saves into a string called "output". But for some of them it does not save anything. We will need to go over this in class tomorrow.

![image](https://cloud.githubusercontent.com/assets/16885928/14412894/2433a6ee-ff31-11e5-8878-34410bbaaa31.png)

**Comment by nadusumilli-unomaha** [comment]
I just changed oneshot at one place. I have made the changes please check and it should work.
