### ISSUE TITLE
create unit tests

### ISSUE THREAD

**Issue by bwolatz** [bwolatz/CSCI4900#39]
I'm happy to do this, but if you could give some pointers that would be cool

**Comment by nadusumilli-unomaha** [comment]
Its basically just testing each method in our program. You can hand write the pseudo code which shows how you will test to see if each method works. He actually gave examples of how to do it in the slides he gave today

**Comment by bwolatz** [comment]
just got home for the day.. sorry I've been lagging behind you on this assignment. I'm currently breaking up the dependency.py file into more than just "getDependenciesAndScan" for easier unit testing
