### ISSUE TITLE
create printing of relationships from database.

### ISSUE THREAD

**Issue by bwolatz** [bwolatz/CSCI4900#40]
I can do this too should be easy editing of dependency.py

**Comment by nadusumilli-unomaha** [comment]
You actually should query the dosocs database and print the document.

**Comment by nadusumilli-unomaha** [comment]
That's good that you are getting the information into the DB. How will I see this information without having to root through the DB? Make sure you help me understand how the data is in there and how I can see that data.  (This is what the professor said about printing the information.)

**Comment by bwolatz** [comment]
not really sure how to do this one. I think this will be one that we wont have done for the assignment, we'll have to talk about it

**Comment by bwolatz** [comment]
been done for a while.
