### ISSUE TITLE
submit email with pointer to correct dosocs fork

### ISSUE THREAD

**Issue by bwolatz** [bwolatz/CSCI4900#41]
when the assignment is complete

**Comment by nadusumilli-unomaha** [comment]
create new release version before submission for both dosmav and dosocs2

**Comment by bwolatz** [comment]
so the pointer to the correct fork of dosocs2 is https://github.com/nadusumilli/DoSOCSv2 ?

**Comment by nadusumilli-unomaha** [comment]
yes the correct dosocs version is in my account and that is the pointer to
it.

**Comment by bwolatz** [comment]
submitting now
