### ISSUE TITLE
Update PowerPoint before presentation date

### ISSUE THREAD

**Issue by bwolatz** [bwolatz/CSCI4900#45]
Add in your "problems and complexities", as well as your solutions to those problems.

We'll need to ask Matt what he wants to have for the "Solution Highlights" slide.

Here are the points that we are supposed to have

i.  Introduce your group 
ii. Discuss the goals that you accomplished in the project 
iii.    Highlights of your solution 
iv. Complexities encountered in your design/development 
v.  Creative solutions to address these complexities in your solution 
vi. Your work contributing to the SPDX community

And it has to have 8 slides

[CSCI4900-Presentation.pptx](https://github.com/bwolatz/CSCI4900/files/228493/CSCI4900-Presentation.pptx)

**Comment by bwolatz** [comment]
Just need the slide of your complications (and update solutions to complexities slide

[CSCI4900-Presentation.pptx](https://github.com/bwolatz/CSCI4900/files/228599/CSCI4900-Presentation.pptx)

**Comment by nadusumilli-unomaha** [comment]
added my part to the slides
